name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP with composer and phpunit
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: bcmath
          tools: phpunit:9.5, composer:v2

      - name: Composer install
        run: composer install --prefer-dist --no-interaction --profile

      - name: Test with phpunit
        run: vendor/bin/phpunit --coverage-text
